### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by codecaiine** [codecaiine/recipe-app#12]
Set up Kanban board

There is  only one (1) member in this project:

@codecaiine 

Link to project: https://github.com/codecaiine/recipe-app/projects/1

**Comment by Emmyn5600** [comment]
Hi @codecaiine 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 

##  Optional suggestion

-  N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
